name: Markdown to PDF

on: push

jobs:
  markdown_to_pdf_via_pandoc:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: docker://ghcr.io/dygv/pandoc/ja:latest
        with: 
          args: memo/title.md memo/create_env.md memo/ex1.md memo/ex2.md memo/ex3.md memo/srv_cli.md memo/gazebo_turtlebot3.md -o ROS_memo.pdf -f markdown --template eisvogel --listings --pdf-engine=xelatex --toc --listings -s -N -V linkcolor=blue -V toc-own-page=true -V titlepage=true -V CJKmainfont=IPAexGothic
      - name: commit
        run : |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          git add .
          git commit --author=. -m "update pdf"
          git push
      - uses: actions/upload-artifact@master
        with:
          name: ROS_memo
          path: ROS_memo.pdf

